export const selectedItems = [
  {
    id: 1,
    name: "Family Feast Combo",
    description: "Perfect for sharing! Includes 2 main dishes, 2 sides, and 2 drinks. Great value for families.",
    price: 45.99,
    savings: 12.5,
    items: ["Butter Chicken", "Margherita Pizza", "Caesar Salad", "Mushroom Risotto", "2 Soft Drinks"],
    category: "Family",
    popularity: 85,
  },
  {
    id: 2,
    name: "Date Night Special",
    description: "Romantic dinner for two with appetizer, two mains, dessert, and wine pairing.",
    price: 68.99,
    savings: 18.0,
    items: ["Garlic Bread", "Butter Chicken", "Mushroom Risotto", "Tiramisu", "House Wine"],
    category: "Couples",
    popularity: 92,
  },
  {
    id: 3,
    name: "Quick Lunch Deal",
    description: "Fast and delicious lunch combo with main, side, and drink. Perfect for busy schedules.",
    price: 18.99,
    savings: 5.5,
    items: ["Caesar Salad", "Garlic Bread", "Soft Drink"],
    category: "Lunch",
    popularity: 78,
  },
  {
    id: 4,
    name: "Vegetarian Delight",
    description: "Plant-based combo featuring our best vegetarian dishes with fresh ingredients.",
    price: 32.99,
    savings: 8.75,
    items: ["Mushroom Risotto", "Caesar Salad", "Margherita Pizza", "Fresh Juice"],
    category: "Vegetarian",
    popularity: 71,
  },
  {
    id: 5,
    name: "Pizza Party Pack",
    description: "Great for groups! Three different pizzas with sides and drinks for everyone.",
    price: 89.99,
    savings: 25.0,
    items: ["Margherita Pizza", "Pepperoni Pizza", "Veggie Pizza", "Garlic Bread", "4 Soft Drinks"],
    category: "Group",
    popularity: 88,
  },
  {
    id: 6,
    name: "Healthy Choice Combo",
    description: "Nutritious and delicious combination of fresh salads and grilled items.",
    price: 28.99,
    savings: 7.25,
    items: ["Caesar Salad", "Grilled Chicken", "Fresh Fruit", "Sparkling Water"],
    category: "Healthy",
    popularity: 65,
  },
]
